apiVersion: apps/v1
kind: Deployment
metadata: 
  name: attacker-deployment
  namespace: default
  labels:
    app: attacker-label
spec:
  replicas: 1 
  selector:    
    matchLabels:
      app: attacker-label
  template: 
    metadata:
      labels:
        app: attacker-label
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: attacker-container
        image: shkch.duckdns.org/webserver/attacker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
    