apiVersion: apps/v1
kind: Deployment
metadata: 
  name: attacker-deployment
  namespace: default
  labels:
    app: attacker-label
spec:
  replicas: 1 
  selector:    
    matchLabels:
      app: attacker-label
  template: 
    metadata:
      labels:
        app: attacker-label
    spec:
      imagePullSecrets:
      - name: harbor-creds
      serviceAccountName: admin-server-sa
      containers:
      - name: attacker-container
        image: "shkch.duckdns.org/webserver/attacker:latest"
        volumeMounts:
        - name: attacker-volume
          mountPath: /tmp/
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
      volumes:
      - name: attacker-volume
        hostPath: /tmp/